# Generated by Django 6.0.3 on 2026-09-22 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoItemInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('categoria', models.CharField(choices=[('equipo', 'Equipo'), ('mecanico', 'Mecánico'), ('documentacion', 'Documentación')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('medida_preventiva_default', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('licencia_conduccion_vigente_hasta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tiempo_estimado', models.DurationField(blank=True, null=True)),
                ('descripcion_ruta', models.TextField(blank=True)),
                ('instrucciones_recorrido', models.TextField(blank=True)),
                ('mapa_imagen', models.FileField(blank=True, null=True, upload_to='rutas/mapas/')),
                ('geometria_ruta', models.JSONField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('tipo', models.CharField(max_length=150)),
                ('soat_vigente_hasta', models.DateField()),
                ('revision_tecnomecanica_hasta', models.DateField()),
                ('seguro_carga_hasta', models.DateField(blank=True, null=True)),
                ('licencia_transito_vigente', models.BooleanField(default=True)),
                ('id_objeto_gps', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Desplazamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desplazamiento', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('hora_llegada_estimada', models.TimeField()),
                ('hora_llegada_real', models.TimeField(blank=True, null=True)),
                ('estado_emparejamiento', models.CharField(choices=[('sin_gps', 'Sin datos GPS aún'), ('auto', 'Emparejado automáticamente (único candidato)'), ('manual', 'Emparejado manualmente'), ('pendiente', 'Ambiguo — requiere revisión manual')], default='sin_gps', max_length=20)),
                ('tiempo_conduccion_sin_descanso', models.CharField(blank=True, max_length=100)),
                ('tiempos_descanso_programados', models.TextField(blank=True)),
                ('condiciones_climaticas_esperadas', models.CharField(blank=True, max_length=300)),
                ('puntos_parada_segura', models.TextField(blank=True)),
                ('alcoholemia_fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('alcoholemia_resultado', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desplazamientos', to='rutas.conductor')),
                ('planificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desplazamientos_planificados', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desplazamientos', to='rutas.ruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desplazamientos', to='rutas.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='InspeccionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('realizada_por', models.CharField(blank=True, max_length=200)),
                ('resultado_general', models.CharField(choices=[('apto', 'Apto'), ('apto_observaciones', 'Apto con observaciones'), ('no_apto', 'No apto')], default='apto', max_length=20)),
                ('desplazamiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspeccion', to='rutas.desplazamiento')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteGPSImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_original', models.FileField(upload_to='gps/importaciones/')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_cubierta', models.DateField(blank=True, null=True)),
                ('fecha_fin_cubierta', models.DateField(blank=True, null=True)),
                ('importado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_importados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('punto_critico', 'Punto crítico'), ('interseccion', 'Intersección'), ('zona_escolar', 'Zona escolar'), ('zona_urbana', 'Zona urbana'), ('cuerpo_agua', 'Cuerpo de agua'), ('punto_emergencia', 'Punto de emergencia'), ('hospital', 'Hospital'), ('estacion_servicio', 'Estación de servicio'), ('otro', 'Otro')], max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('referencia_km', models.CharField(blank=True, max_length=50)),
                ('orden', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='rutas.ruta')),
            ],
            options={
                'ordering': ['ruta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarjeta_ruta', 'Tarjeta de Ruta (Excel)'), ('control_planificacion', 'Control de Planificación (Word)')], max_length=25)),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('desplazamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_generados', to='rutas.desplazamiento')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_generados', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_generados', to='rutas.ruta')),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('direccion_origen', models.CharField(blank=True, max_length=300)),
                ('direccion_destino', models.CharField(blank=True, max_length=300)),
                ('coordenadas_inicio', models.CharField(blank=True, max_length=100)),
                ('coordenadas_fin', models.CharField(blank=True, max_length=100)),
                ('distancia_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duracion_total', models.DurationField(blank=True, null=True)),
                ('velocidad_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('velocidad_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tiempo_movimiento', models.DurationField(blank=True, null=True)),
                ('tiempo_ralenti', models.DurationField(blank=True, null=True)),
                ('tiempo_actividad', models.DurationField(blank=True, null=True)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='rutas.ruta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='rutas.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_gps', models.CharField(max_length=50)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('direccion_inicio', models.CharField(blank=True, max_length=300)),
                ('direccion_fin', models.CharField(blank=True, max_length=300)),
                ('coordenadas_inicio', models.CharField(blank=True, max_length=100)),
                ('coordenadas_fin', models.CharField(blank=True, max_length=100)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('distancia', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('velocidad_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('velocidad_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tiempo_movimiento', models.DurationField(blank=True, null=True)),
                ('tiempo_ralenti', models.DurationField(blank=True, null=True)),
                ('tiempo_actividad', models.DurationField(blank=True, null=True)),
                ('reporte_importado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='rutas.reportegpsimportado')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='rutas.viaje')),
            ],
        ),
        migrations.AddField(
            model_name='desplazamiento',
            name='viaje_gps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desplazamientos', to='rutas.viaje'),
        ),
        migrations.CreateModel(
            name='ItemInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('no_aplica', 'No aplica')], max_length=15)),
                ('observacion', models.TextField(blank=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rutas.inspeccionvehiculo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutas.catalogoiteminspeccion')),
            ],
            options={
                'unique_together': {('inspeccion', 'item')},
            },
        ),
        migrations.CreateModel(
            name='RutaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida_preventiva_especifica', models.TextField(blank=True)),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='rutas.catalogoriesgo')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='rutas.ruta')),
            ],
            options={
                'unique_together': {('ruta', 'riesgo')},
            },
        ),
    ]
