# Generated by Django 6.0.3 on 2026-09-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='distancia_osrm_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='geometria_osrm',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
