# Generated by Django 6.0.3 on 2026-09-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_viaje_distancia_osrm_km_viaje_geometria_osrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccionvehiculo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
