# Generated by Django 6.0.3 on 2026-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_inspeccionvehiculo_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='condiciones_generales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ruta',
            name='cuerpos_de_agua',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='puntos_apoyo_emergencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='restriccion_desde',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='restriccion_dias',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ruta',
            name='restriccion_hasta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tiene_restriccion_horario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tipo_superficie',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ruta',
            name='trafico',
            field=models.CharField(blank=True, choices=[('camiones', 'Mayoría camiones'), ('automoviles', 'Mayoría automóviles'), ('mixto', 'Mixto')], max_length=20),
        ),
        migrations.AddField(
            model_name='ruta',
            name='visibilidad',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
