# Generated by Django 6.0.3 on 2026-09-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_ruta_condiciones_generales_ruta_cuerpos_de_agua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='pasos_osrm',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
