# Generated by Django 6.0.3 on 2026-09-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0005_viaje_pasos_osrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='desplazamiento',
            name='cache_entorno',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desplazamiento',
            name='cache_entorno_actualizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
