# Generated by Django 5.1.7 on 2026-09-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0007_vehiculo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
