# Generated by Django 5.1.7 on 2026-09-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0008_conductor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
    ]
