# Generated by Django 5.1.7 on 2026-10-01 14:20

import rutas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0009_vehiculo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=15, unique=True, validators=[rutas.models.validar_placa]),
        ),
    ]
